# ============================================================
# ECOWAS Border Intelligence Analytics Platform
# Downloads
# ============================================================

# ============================================================
# Chapter 1 - Import Libraries
# ============================================================

import streamlit as st
import pandas as pd
from pathlib import Path

# ============================================================
# Chapter 2 - Page Configuration
# ============================================================

st.set_page_config(
    page_title="Downloads",
    page_icon="📥",
    layout="wide"
)

# ============================================================
# Chapter 3 - Header
# ============================================================

st.title("📥 Downloads")

st.caption(
    "Download datasets generated by the ECOWAS Border Intelligence Analytics Platform."
)

st.markdown("---")

# ============================================================
# Chapter 4 - Download Trade Transactions
# ============================================================

trade = pd.read_csv(
    Path("data") / "trade_diversion_transactions.csv"
)

st.download_button(
    "📄 Trade Transactions",
    trade.to_csv(index=False).encode("utf-8"),
    "trade_diversion_transactions.csv",
    "text/csv"
)

# ============================================================
# Chapter 5 - Download Performance Scorecard
# ============================================================

scorecard = pd.read_csv(
    Path("outputs") / "border_performance_scorecard.csv"
)

st.download_button(
    "🏆 Border Performance Scorecard",
    scorecard.to_csv(index=False).encode("utf-8"),
    "border_performance_scorecard.csv",
    "text/csv"
)

# ============================================================
# Chapter 6 - Download Border Summary
# ============================================================

summary = trade.groupby("Border_Post")[
    "Trade_Value_USD"
].sum().reset_index()

st.download_button(
    "🌍 Border Trade Summary",
    summary.to_csv(index=False).encode("utf-8"),
    "border_trade_summary.csv",
    "text/csv"
)

# ============================================================
# Chapter 7 - Download Commodity Summary
# ============================================================

commodity = trade.groupby("Commodity")[
    "Trade_Value_USD"
].sum().reset_index()

st.download_button(
    "📦 Commodity Summary",
    commodity.to_csv(index=False).encode("utf-8"),
    "commodity_summary.csv",
    "text/csv"
)